config/routes.rb
Rails.application.routes.draw do
	root 'lists#index'

	devise_for :users

	resources :lists do
		resources :tasks do
			put :complete, on: :member
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :title, presence: true

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  def complete!
    self.completed = true
    save
  end

  validates :title, presence: {message: "can't be blank!"}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @lists = current_user.lists if user_signed_in?
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new list_params

    redirect_to lists_path, :notice => "List saved!" if @list.save
  end

  def edit
    @list = List.find params[:id]
  end

  def update
    @list = List.find params[:id]

    @list.update list_params

    redirect_to lists_path
  end

  def destroy
    @list = List.find params[:id]

    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  helper_method :task, :list, :tasks

  def create
    task.assign_attributes(task_params)

    redirect_to list_tasks_path(list), :notice => "Task saved!" if task.save
  end

  def update
    task.update task_params

    redirect_to list_tasks_path(list)
  end

  def complete
    task.complete!

    redirect_to list_tasks_path(list)
  end

  def destroy
    task.destroy

    redirect_to list_tasks_path(list)
  end

  private

  delegate :tasks, to: :list, private: true

  def task
    @task ||= params[:id] ? tasks.find(params[:id]) : tasks.new
  end

  def list
    @list ||= List.find params[:list_id]
  end

  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div id="user_nav" class='buffer-top'>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'btn btn-primary'%> 
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
        <% else %>
          <%= link_to "Sing up", new_user_registration_path, class: 'btn btn-primary' %> 
          <%= link_to "Login", new_user_session_path, class: 'btn btn-primary' %>
        <% end %> 
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <div class="row">
        <%= yield %>    
      </div>
    </div>
  
  </body>
</html>

app/views/lists/_form.html.erb
<div class="col-md-6">
  <%= simple_form_for @list do |f| %>
    <p><%= f.input :title %></p>
    <p><%= f.button :submit %></p>
  <% end %>
</div>

app/views/lists/_list.html.erb
<div class="list">
  <p>
    <span class="title"><%= list.title %></span>
    <%= link_to content_tag('span', '', class: 'fa fa-folder-open'), list_tasks_path(list), class: 'action edit' %>
    <%= link_to content_tag('span', '', class: 'fa fa-edit'), edit_list_path(list), class: 'action edit' %>
    <%= link_to content_tag('span', '', class: 'fa fa-trash'), list, method: :delete, class: 'action edit' %>
  </p>
</div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<div class="col-md-12">
  <h2>Edit List</h2>
</div>

<%= render 'form' %>

app/views/lists/index.html.erb
<div class="col-md-12">
  <h1>ToDo List</h1>

  <div class="buffer-top"><%= link_to "New List", new_list_path, class: 'btn btn-primary' %></div>
  <% if user_signed_in? %>
    <div class="buffer-top">
      <% @lists.each do |list| %>
        <%= render partial: 'list', object: list %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="col-md-12">
  <h2>New List</h2>
</div>  

<%= render 'form' %>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/tasks/_task.html.erb
<div class="task completed_<%= task.completed %>">
  <p>
    <span class="title"><%= task.title %></span>
    <%= link_to content_tag('span', '', class: 'fa fa-check-square-o'), complete_list_task_path(list, task), data:{method: :put}, class: 'action edit done' %>
    <%= link_to content_tag('span', '', class: 'fa fa-edit'), edit_list_task_path(list, task), class: 'action edit' %>
    <%= link_to content_tag('span', '', class: 'fa fa-trash'), list_task_path(list, task), method: :delete, class: 'action edit' %>
  </p>
</div>

app/views/tasks/complete.html.erb
<h1>Tasks#complete</h1>
<p>Find me in app/views/tasks/complete.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="col-md-12">
  <h2>Edit Task</h2>
</div>

<div class="col-md-6">
  <%= simple_form_for task, url: list_task_path(list, task), method: :put do |f| %>
    <p><%= f.input :title %></p>
    <p><%= f.input :completed %></p>
    <p><%= f.button :submit %></p>
  <% end %>

</div>

app/views/tasks/index.html.erb
<div class="col-md-12">
  <h2>List: <%= list. title %></h2>

  <div class="buffer-top"><%= link_to "New Task", new_list_task_path(list), class: 'btn btn-primary' %>
  <%= link_to "Back to Lists", lists_path, class: 'btn btn-primary' %></div>

  <div class="buffer-top">
    <% tasks.each do |task| %>
      <%= render partial: 'task', object: task %>
    <% end %>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="col-md-12">
  <h2>New Task</h2>
</div>  

<div class="col-md-6">
  <%= simple_form_for task, url: list_tasks_path(list), method: :post do |f| %>
    <p><%= f.input :title %></p>
    <p><%= f.input :completed %></p>
    <p><%= f.button :submit %></p>
  <% end %>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>